services:
  server:
    build:
      context: .
    container_name: fastapicontainer
    image: fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
    env_file:
      - .env